apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: social-media-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: social-media-backend
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
